### PR TITLE
Update Froogaloop library

### PR DESCRIPTION
**Pull request by bdougherty**
We'll be activating [HSTS](https://developer.mozilla.org/en-US/docs/Web/Security/HTTP_strict_transport_security) on Vimeo soon and the current version of Froogaloop won't work when we do that. This updates it to a new version (vimeo/player-api@f433dfe16446b10925c0d907c987257c12ef86f7) that will support HSTS properly.

We have no official timeline, but it will be relatively soon (in the next month or so probably).

### CODE REVIEW

**Comment by davekiss** [comment]
Thanks for the heads up, @bdougherty!

**Comment by davekiss** [comment]
@bdougherty Getting some support requests from users regarding this change, I believe. Is the Player API still compatible with IE?


> Visitors on Windows IE 10 aren't able to play videos. I'm seeing this error in the console:

> Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://player.vimeo.com') does not match the recipient window's origin ('http://motionographer.com').
froogaloop2.min.js:1 Uncaught TypeError: Cannot read property 'ready' of undefined

> I suspect this has something to do with using https (instead of http) for oEmbed?

**Comment by bdougherty** [comment]
@davekiss should be. Do you have a link to a specific page where it's not working so I can check it out?

**Comment by davekiss** [comment]
@bdougherty see motionographer.com/inspiration/

**Comment by davekiss** [comment]
@bdougherty any ideas here?

**Comment by davekiss** [comment]
+@justincone

**Pull request closed without merging**
